### ISSUE TITLE
sw_video.mp4 could not be found

### ISSUE THREAD

**Issue by biyuehuang** [averdones/star_wars_object_detection#1]
Hi, thank you for your kindly sharing. I follow the commands and it work. But object_detection_sw.ipynb miss sw_video.mp4. Could you share a link to download it?

**Comment by averdones** [comment]
Hey. Sorry, I can't find the original video anymore, It's been a long time. But you can use any video you like, like [this one](https://www.youtube.com/watch?v=I6Y9PPJNdkg), for example.

You can download it using "youtube_dl". Just do:

`pip install --upgrade youtube_dl`
`youtube-dl -f 18 https://www.youtube.com/watch?v=I6Y9PPJNdkg`

Hope it helps.
